# This is a basic workflow to help you get started with Actions

name: DEPLOY

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: [self-hosted, linux]
    
    strategy:
      matrix:
        node-version: [12.x]
      
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
  
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: echo ${{ secrets.DOT_ENV }} | base64 --decode > ./.env
      - run: ls -al
      - run: pwd
      - run: npm run deploy
      - run: sudo pm2 start ./dist/app.js
      
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always() # Pick up events even if the job fails or is canceled.
